### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by atisharma** [Calysto/calysto_hy#21]
Presumably because of the changes in Hy?

In a venv, I followed the readme instructions,

```
(Python 3.9.13) ati@neptune ~/hytest > pip3 install git+https://github.com/ekaschalk/jedhy.git
[...]
(Python 3.9.13) ati@neptune ~/hytest > pip3 install git+https://github.com/Calysto/calysto_hy.git
[...]

(Python 3.9.13) ati@neptune ~/hytest > python3 -m calysto_hy install --sys-prefix
Traceback (most recent call last):
  File "/home/ati/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/ati/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/ati/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/ati/hytest/.venv/x86_64-unknown-linux-gnu/Python 3.9.13/lib/python3.9/site-packages/calysto_hy/__init__.py", line 2, in <module>
    from .kernel import CalystoHy
  File "/home/ati/hytest/.venv/x86_64-unknown-linux-gnu/Python 3.9.13/lib/python3.9/site-packages/calysto_hy/kernel.py", line 17, in <module>
    from hy.lex import hy_parse
ModuleNotFoundError: No module named 'hy.lex'
```

**Comment by actsasgeek** [comment]
I've tried to futz with this for an hour (full disclosure, I had only the vaguest idea as to what I was doing). Hy's internals have changed a lot since Calysto Hy's last commit. It's unfortunate because lack of Jupyter support is a deal breaker for using Hy.

**Comment by paulocesarcuneo** [comment]
it appear to be using hy 1.0.X
```
git clone git@github.com:hylang/hy.git
git checkout 1.0a4
pip install -e .
python3 -m calysto_hy install --user
```

**Comment by actsasgeek** [comment]
Since none of the Hy Calysto code has been changed in 2 years, I don't think it's using version 1.0.X. When I checked out hy and did a `git branch -a` there is no 1.0a4 branch listed, just stable and master.

I was able to get it some of it working with by changing:

https://github.com/Calysto/calysto_hy/blob/master/calysto_hy/kernel.py#L136-L146

to:

```
from hy.reader import read_many
from hy.compiler import hy_eval
...
def do_execute(self, code):
...
            hy_model = read_many(code, filename=filename)
            self.result = hy_eval(hy_model, locals=self.locals)
...
```
However, there are still issues:

1. it appears that user defined macros don't work
2. code completion doesn't work

I was working on code completion when I discovered the macro issue.

I'm not sure how the default completer is working. I just went straight to `jedhy`. Unfortunately, jedhy has also not been updated in 4-5 years and `hy` has changed a lot since then. The syntax for `require` and `import` are different and `deftag` was eliminated.

**Comment by actsasgeek** [comment]
There is actually a PR for a version that works with 0.24 + but it hasn't been merged. You can install it directly:

```
 pip install git+https://github.com/fergusq/calysto_hy.git@hy-0.24.0-support --upgrade
```

You may need to add --force-reinstall but be careful as that is recursive to all dependencies ☹️ The default code completion works but not `jedhy` for the reasons described above.

User defined macros still don't (appear?) to work. It's interesting that the test notebook doesn't have any macro definitions in it. There are other reported issues about macros and fixes so maybe something broke again?
